# Generated by Django 4.0.4 on 2022-06-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='description',
            field=models.CharField(default=None, max_length=300, null=True, verbose_name='Описание заведения'),
        ),
    ]
