# Generated by Django 4.0.4 on 2022-06-08 18:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cafe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='worday_start_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='cafe',
            name='workday_end_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
