# Generated by Django 4.0.4 on 2022-06-08 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cafe_worday_start_time_cafe_workday_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='worday_start_time',
            new_name='workday_start_time',
        ),
    ]
