# Generated by Django 4.0.4 on 2022-06-08 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_worday_start_time_cafe_workday_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='workday_end_time',
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
    ]
